CREATE TABLE IF NOT EXISTS ENDERECO (ID int AUTO_INCREMENT PRIMARY KEY, RUA varchar (255),
 NUMERO varchar (255), CIDADE varchar (255), ESTADO varchar (255));

CREATE TABLE IF NOT EXISTS PACIENTE (ID int AUTO_INCREMENT PRIMARY KEY, NOME varchar (255),
 SOBRENOME varchar (255), RG varchar (255), DATA_CADASTRO TIMESTAMP WITHOUT TIME ZONE,
  ENDERECO_ID int);

CREATE TABLE IF NOT EXISTS DENTISTA (ID int AUTO_INCREMENT PRIMARY KEY, NUMERODEMATRICULA,
 NOME varchar (255), SOBRENOME varchar (255));


